### ISSUE TITLE
Review Survey and tune for Diebetes

### ISSUE THREAD

**Issue by gjwgit** [kimishidairessha/diabetes#10]

**Comment by kimishidairessha** [comment]
![Image](https://github.com/kimishidairessha/diabetes/assets/138195672/12d21ed3-041a-43d6-acea-5c5707045ce1)



![Image](https://github.com/kimishidairessha/diabetes/assets/138195672/df55d749-29cb-4392-8486-c35ef29c25b9)



![Image](https://github.com/kimishidairessha/diabetes/assets/138195672/33db09d7-7b9b-4d1f-b4a6-d9a8153fe3d8)

Show the whole tool tip data in both Systolic and Diastolic & add a scrollable widget to display the large data set & Decrease the width of the range columns.

**Comment by kimishidairessha** [comment]
The whole survey showed in #9

**Comment by gjwgit** [comment]
Noting the plots can now scroll. Going back 2 weeks. Looks good.
