### ISSUE TITLE
SETTINGS: Add a settings page to save my encryption key

### ISSUE THREAD

**Issue by gjwgit** [kimishidairessha/diabetes#11]
## Description

Instead of having to remember my encryption key add a new Settings page that allows me to store the encryption key there and save it using flutter_secure_storage, so next time I start the app it gets the encryption key from the secure storage.

## Why

So that the user does not have to remember the encryption key and so has a better experience.

## Closing Criteria

- [ ] New Settings page
- [ ] TextField for entry of secret encryption key
- [ ] On startup the saved encryption key populates the TextField
- [ ] The encryption key is not prompted for any more

**Comment by kimishidairessha** [comment]
![Image](https://github.com/kimishidairessha/diabetes/assets/138195672/df797129-8113-42cc-b38f-a885b3f26bdf)

**Comment by gjwgit** [comment]
Can we have an "eye" to toggle whether the key is shown or `*******` is shown.

**Comment by gjwgit** [comment]
Use `flutter_secure_storage` package to store the key on the local device so that when I log in next time the key is obtained from the device local storage rather than the user having to type it in again.

**Comment by kimishidairessha** [comment]
When the user types the enc-key into the textfiled in the setting page and tap the "save" button, then the key will be saved on the local device. When the user logs in again, the login screen automatically enters the locally saved enc-key. The user does not need to enter the enc-key again (the input content can be changed).

![Image](https://github.com/kimishidairessha/diabetes/assets/138195672/8595ef63-617a-4230-ada8-0f990d43848b)
![Image](https://github.com/kimishidairessha/diabetes/assets/138195672/186ef312-a214-4980-a496-d57504f557c1)
![Image](https://github.com/kimishidairessha/diabetes/assets/138195672/f1f5a5aa-8261-4645-9fc5-f529b87474ee)



![Image](https://github.com/kimishidairessha/diabetes/assets/138195672/7b484ab9-ce54-4656-9408-af2402f7272b)
![Image](https://github.com/kimishidairessha/diabetes/assets/138195672/2144e386-1885-44d8-b9ad-ffdf96e5f6ab)
