### ISSUE TITLE
TOOLTIPS: Values seem to be incorrect

### ISSUE THREAD

**Issue by gjwgit** [kimishidairessha/diabetes#13]
## Description

The tooltips do not seem to have the correct values. I entered 105/75 for systolic/diastolic but the tool tip is different. It is als missing the date.

![Image](https://github.com/kimishidairessha/diabetes/assets/1681429/7f22fe64-45a0-4967-a185-bdcb33e8c103)

**Comment by gjwgit** [comment]
After a restart I noticed the data was now correct? Is there a bug?



![Image](https://github.com/kimishidairessha/diabetes/assets/1681429/6a490b83-017b-40d9-8ac1-b0ccecfe72df)

**Comment by kimishidairessha** [comment]
Explicitly force the chart to refresh to fix the error where the initial tooltip did not display the correct date and the error where dragging the X-axis curve would deform.


![Image](https://github.com/kimishidairessha/diabetes/assets/138195672/81f2217f-6158-4138-8c9c-b92da6466119)
![Image](https://github.com/kimishidairessha/diabetes/assets/138195672/16854cc8-3a40-4ccd-b0f6-20063ce67876)
![Image](https://github.com/kimishidairessha/diabetes/assets/138195672/a808bf05-1b41-48ce-9518-bc0653534ee5)
