### ISSUE TITLE
HOME: Make the home page more attractive

### ISSUE THREAD

**Issue by gjwgit** [kimishidairessha/diabetes#14]
## Description

There is an opportunity to make the HOME page  more attractive

![Image](https://github.com/kimishidairessha/diabetes/assets/1681429/93490caf-c666-4b2d-a5f2-d49f937a420a)

**Comment by gjwgit** [comment]
Here's an example from another app, but choose what you like.



![Image](https://github.com/kimishidairessha/diabetes/assets/1681429/399050ee-4ae0-4a64-806f-33760e1b8a1a)

**Comment by kimishidairessha** [comment]
![Image](https://github.com/kimishidairessha/diabetes/assets/138195672/3f738913-4f45-4f50-9645-e42dc68d083b)
![Image](https://github.com/kimishidairessha/diabetes/assets/138195672/27b4f002-7111-4de3-847a-aaeb56c6c977)

**Comment by gjwgit** [comment]
Can we add an action to each Text box so that when it is tapped we go to that page.

**Comment by kimishidairessha** [comment]
Add an action to each Text box so that when it is tapped we go to that page.

**Comment by gjwgit** [comment]
Wating to merge the PR for activating the Text boxes
