### ISSUE TITLE
STYLE: Change background colour to same as login page

### ISSUE THREAD

**Issue by gjwgit** [kimishidairessha/diabetes#17]
# Description

The first login page has a nice colour background. All others are white. Use the same soft orange background throughout.

**Comment by kimishidairessha** [comment]
![Image](https://github.com/kimishidairessha/diabetes/assets/138195672/7affc052-d3a0-4dc7-84e9-c1a4f9556fc4)
![Image](https://github.com/kimishidairessha/diabetes/assets/138195672/e34d699b-6c5f-4846-b7a5-fe673999cb24)
![Image](https://github.com/kimishidairessha/diabetes/assets/138195672/38ba1e5d-45f7-45a4-9ac5-874363fc9896)
![Image](https://github.com/kimishidairessha/diabetes/assets/138195672/ee1f6d5f-f2a2-472b-b01d-fcdec1701271)
![Image](https://github.com/kimishidairessha/diabetes/assets/138195672/1f11abc5-1983-44a9-a9d5-55d67aeb1846)
