### ISSUE TITLE
POD: Make the line transparent.

### ISSUE THREAD

**Issue by kimishidairessha** [kimishidairessha/diabetes#18]

**Comment by kimishidairessha** [comment]
![Image](https://github.com/kimishidairessha/diabetes/assets/138195672/bd587e36-6891-4f9e-bfc2-e5597cbfd907)

**Comment by gjwgit** [comment]
Much nicer. Thanks. I think I would prefer that if there is no value recorded for a particular day then we don't show it as 0. That could be misleading.

**Comment by gjwgit** [comment]
.
