### ISSUE TITLE
CHARTS: Tooltips should pop down more quickly

### ISSUE THREAD

**Issue by gjwgit** [kimishidairessha/diabetes#21]
# Description

The tooltips in the charts stay up for too long and hinder me looking at other points in a chart. Can we reduce the length of time the tooltip stays up - I expect it to pop down when I move my mouse away from the point.

![Image](https://user-images.githubusercontent.com/1681429/263407265-0491f2c8-937d-4b72-9a45-81ec08eeab48.png)

# Why

So that we conform to the user's expectations

# Closing Criteria

- [ ] Tooltips disappear when the mouse moves away from the point.

**Comment by kimishidairessha** [comment]
When the chart is scrollable and displayed, the tooltip will be truncated because it is too long. I have not yet thought of how to solve it.


![Image](https://github.com/kimishidairessha/diabetes/assets/138195672/cac309f4-a54b-436c-bddc-584fc5bd809e)



![Image](https://github.com/kimishidairessha/diabetes/assets/138195672/9852bb61-02d2-45f3-924f-e5eee19a069c)

**Comment by gjwgit** [comment]
This will be updated once migrated to fl_chart.

**Comment by kimishidairessha** [comment]
Change all syncfusion charts to fl_chart. And for the line chart, change it to the dot chart.Solved the problem of displaying points in a table with a empty value.


![Image](https://github.com/kimishidairessha/diabetes/assets/138195672/c97095f6-fcae-46b7-9995-860697f7fa5b)
![Image](https://github.com/kimishidairessha/diabetes/assets/138195672/3a9787e0-1ae2-4e39-b69e-d18e26302fed)
![Image](https://github.com/kimishidairessha/diabetes/assets/138195672/3d151dc6-da03-465b-8a19-8d20a21d6be4)
![Image](https://github.com/kimishidairessha/diabetes/assets/138195672/13dcf6a9-8598-40ed-b9a7-bffca1805115)

**Comment by gjwgit** [comment]
Looking good. But only move to In review once there is a PR. Thanks,

**Comment by gjwgit** [comment]
Merged. Closing.
