### ISSUE TITLE
SURVEY: Support TAB to go to next field

### ISSUE THREAD

**Issue by gjwgit** [kimishidairessha/diabetes#23]
# Description

This is primarily for the desktop version.

# Why

So that the user has a familiar experience on the desktop

# Closing Criteria

- [ ] Test that from one field, a TAB will take me to the next field in the survey.

**Comment by kimishidairessha** [comment]
![Image](https://github.com/kimishidairessha/diabetes/assets/138195672/9258f4d9-55dc-48f0-a21e-9ca0b52b75a5)
![Image](https://github.com/kimishidairessha/diabetes/assets/138195672/960912a7-2281-4c52-a5e7-ec0156cc0f2e)

**Comment by gjwgit** [comment]
Testing on desktop (less relevant for mobile):

When I go to the SURVEY page and press tab the first time, it should go to the 0 radio button, then next tab to the 1, etc. all the way through the entries that the use can change.

As the tab down the questions need to automatically scroll the page to keep the focused field in view.

**Comment by gjwgit** [comment]
Press ENTER is a text field to go to the next one.
