### ISSUE TITLE
SETTINGS: webID

### ISSUE THREAD

**Issue by gjwgit** [kimishidairessha/diabetes#44]
# Description

Allow the webID to be viewed and saved on the Settings page. This will be the default value displayed on the login page.

# Why

So that the user can change it in Settings where they might look for it.

# Closing Criteria

- [ ] WedID option on the setting spage.

**Comment by kimishidairessha** [comment]
Show WebID on the setting page and allow users change.

![Image](https://github.com/kimishidairessha/diabetes/assets/138195672/b0fc1071-9506-448e-8e7f-cee04fc68ecd)

**Comment by gjwgit** [comment]
Looks great. Thanks.
