### ISSUE TITLE
Draw Systolic/diastolic on the single plot

### ISSUE THREAD

**Issue by gjwgit** [kimishidairessha/diabetes#5]
## Description

As these two values always come in pairs, let's draw them on the one plot.

## Why

More informative to the user

## Close

- [ ] When we have a chart something like the below

![Image](https://user-images.githubusercontent.com/1681429/250487798-97ffc594-3dd9-40b8-bc81-fff393936851.png)

**Comment by kimishidairessha** [comment]
![Image](https://github.com/kimishidairessha/diabetes/assets/138195672/1c354971-8d72-48f4-8028-ad2b7808d1bc)
