### ISSUE TITLE
SURVEY: Add history report

### ISSUE THREAD

**Issue by kimishidairessha** [kimishidairessha/diabetes#53]
# Description 

Add a history feature that allows users to select the date and time for the completed survey instead of the current time. This could be at the top of the Survey page and by default it is the current date and time.

# Why

So that a user can enter any previous data they may have available from before they started using the app.

# Closing Criteria

- [ ] A user can choose the date for the survey data

**Comment by kimishidairessha** [comment]
Click the button to choose the date and time to add history report. History reports will be added to the pod, in report chronological order instead of adding chronological order. If the user does not click the button, it will be set to current time.


![Image](https://github.com/kimishidairessha/diabetes/assets/138195672/08c0d229-328a-4df3-8285-45015729ecb9)
![Image](https://github.com/kimishidairessha/diabetes/assets/138195672/c7892f5b-61b7-4cf6-93a4-568dcfeeb870)
![Image](https://github.com/kimishidairessha/diabetes/assets/138195672/0c4e6767-3e51-4acb-9ab0-dea22f0df075)
![Image](https://github.com/kimishidairessha/diabetes/assets/138195672/b70b573b-9b5d-4c44-991e-7e6e39431997)
![Image](https://github.com/kimishidairessha/diabetes/assets/138195672/4229fadb-35cb-40ec-89ee-3906429a7665)
![Image](https://github.com/kimishidairessha/diabetes/assets/138195672/f5ca19d6-cf77-43b1-8e31-18a6e862de93)

**Comment by gjwgit** [comment]
Works great. Thanks. I had to fix  `dart format` and `dart analyze` issues though. Best to fix them before creating a PR.
