### ISSUE TITLE
Save application data into the appname folder

### ISSUE THREAD

**Issue by gjwgit** [kimishidairessha/diabetes#7]
## Description

The original app saved the data into a folder called `klee` (the appname). 

Let's now store the data in a folder called `securedialog`

## Why

So that we have our unique location for this app on the SOLID server for the user's POD

## Closing Criteria

- [ ] Folder `securedialog` exists on the server
- [ ] Data is restored and retrieved from that folder

**Comment by kimishidairessha** [comment]
![Image](https://github.com/kimishidairessha/diabetes/assets/138195672/ab47d300-ceb6-4718-9251-d79966ad11f7)
![Image](https://github.com/kimishidairessha/diabetes/assets/138195672/9574a2be-0003-42bd-ac50-2cb8cc3c7644)

**Comment by kimishidairessha** [comment]
![Image](https://github.com/kimishidairessha/diabetes/assets/138195672/4a7e71c3-2585-4ea2-bc9e-66c4925313c0)

**Comment by gjwgit** [comment]
All good. Thanks.
