### ISSUE TITLE
Display all Survey data in the plots

### ISSUE THREAD

**Issue by gjwgit** [kimishidairessha/diabetes#8]
## Description

Load all survey data into the app and display through the charts all data.

## Why

So that a user can view all of their history.

## Closing Criteria

- [ ] Plots show all the available data.

**Comment by kimishidairessha** [comment]
![Image](https://github.com/kimishidairessha/diabetes/assets/138195672/04caeaa5-7a60-4255-a1eb-e919cd8f1c47)
![Image](https://github.com/kimishidairessha/diabetes/assets/138195672/2cc31dd2-25ab-41c3-ad38-ea448c88aeaa)

The chart can scroll left and right to display 15 days of data.

**Comment by gjwgit** [comment]
Great.
