### ISSUE TITLE
Improve the interface for entering the data

### ISSUE THREAD

**Issue by gjwgit** [kimishidairessha/diabetes#9]
![Image](https://github.com/kimishidairessha/diabetes/assets/1681429/70fa71a8-1c4a-4bda-a983-c224310d1adc)

**Comment by kimishidairessha** [comment]
![Image](https://github.com/kimishidairessha/diabetes/assets/138195672/d41404b1-2323-44dd-8f58-d57b187c7906)
![Image](https://github.com/kimishidairessha/diabetes/assets/138195672/e917a6e8-59f7-4e43-a71d-361f58b316b0)

'Weight' has default value

**Comment by gjwgit** [comment]
Tested. All good.
